"""add rag tables

Revision ID: 14c01d5d2d4a
Revises: 2026_09_12_0000
Create Date: 2026-09-30 10:50:00.250193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14c01d5d2d4a'
down_revision: Union[str, None] = '2026_09_12_0000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('visibility', sa.Enum('private', 'shared', 'public', name='collectionvisibility', native_enum=False, length=32), server_default='private', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['User.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'name', name='uq_collections_owner_name')
    )
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collections_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collections_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collections_visibility'), ['visibility'], unique=False)

    op.create_table('collection_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'editor', 'viewer', name='collectionrole', native_enum=False, length=32), server_default='viewer', nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'user_id', name='uq_collection_members_pair')
    )
    with op.batch_alter_table('collection_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_members_collection_id'), ['collection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collection_members_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collection_members_user_id'), ['user_id'], unique=False)

    op.create_table('rag_conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('collection_id', sa.UUID(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rag_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rag_conversations_collection_id'), ['collection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rag_conversations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rag_conversations_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_rag_conversations_user_updated', ['user_id', 'updated_at'], unique=False)

    op.create_table('sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('type', sa.Enum('telegram', 'rss', 'web', 'file', 'api', name='sourcetype', native_enum=False, length=32), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('parser_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('default_collection_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('sync_interval_seconds', sa.Integer(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['User.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['default_collection_id'], ['collections.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index('ix_sources_active_next_sync', ['is_active', 'next_sync_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_default_collection_id'), ['default_collection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_type'), ['type'], unique=False)
        batch_op.create_index('uq_sources_type_external', ['type', 'external_id'], unique=True, postgresql_where=sa.text('external_id IS NOT NULL'))

    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('source_type', sa.Enum('upload', 'telegram', 'rss', 'web', 'api', 'generated', name='documentsourcetype', native_enum=False, length=32), server_default='upload', nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('storage_path', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'chunking', 'embedding', 'indexing', 'ready', 'failed', 'deleted', name='documentstatus', native_enum=False, length=32), server_default='pending', nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['User.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index('ix_documents_collection_hash', ['collection_id', 'content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_collection_id'), ['collection_id'], unique=False)
        batch_op.create_index('ix_documents_collection_status', ['collection_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_status'), ['status'], unique=False)
        batch_op.create_index('uq_documents_source_external', ['collection_id', 'source_id', 'external_id'], unique=True, postgresql_where=sa.text('source_id IS NOT NULL AND external_id IS NOT NULL AND deleted_at IS NULL'))

    op.create_table('rag_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('system', 'user', 'assistant', name='messagerole', native_enum=False, length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('finish_reason', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['rag_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rag_messages', schema=None) as batch_op:
        batch_op.create_index('ix_rag_messages_conversation_created', ['conversation_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_rag_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rag_messages_id'), ['id'], unique=False)

    op.create_table('source_credentials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('credential_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('encrypted_value', sa.Text(), nullable=False),
    sa.Column('key_version', sqlmodel.sql.sqltypes.AutoString(length=32), server_default='v1', nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'credential_type', name='uq_source_credentials_type')
    )
    with op.batch_alter_table('source_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_credentials_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_credentials_source_id'), ['source_id'], unique=False)

    op.create_table('document_acl',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('can_read', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('can_update', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_delete', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_share', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('granted_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['granted_by_id'], ['User.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'user_id', name='uq_document_acl_pair')
    )
    with op.batch_alter_table('document_acl', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_acl_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_acl_granted_by_id'), ['granted_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_acl_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_acl_user_id'), ['user_id'], unique=False)

    op.create_table('document_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('chunking_version', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('embedding_model', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('embedding_version', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('chunk_index >= 0', name='ck_document_chunks_index'),
    sa.CheckConstraint('token_count >= 0', name='ck_document_chunks_tokens'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_document_chunks_position')
    )
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_chunks_document_id'), ['document_id'], unique=False)
        batch_op.create_index('ix_document_chunks_hash', ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_chunks_id'), ['id'], unique=False)

    op.create_table('ingestion_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('job_type', sa.Enum('document_ingest', 'source_sync', 'reindex', 'cleanup', name='jobtype', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('queued', 'processing', 'completed', 'failed', 'cancelled', name='jobstatus', native_enum=False, length=32), server_default='queued', nullable=False),
    sa.Column('current_stage', sa.Enum('parse', 'clean', 'chunk', 'embed', 'index', 'finalize', name='ingestionstagename', native_enum=False, length=32), nullable=True),
    sa.Column('progress', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('celery_task_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('error_code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('progress BETWEEN 0 AND 100', name='ck_ingestion_jobs_progress'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingestion_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_ingestion_jobs_celery_task', ['celery_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_jobs_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_jobs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_jobs_job_type'), ['job_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_jobs_source_id'), ['source_id'], unique=False)
        batch_op.create_index('ix_ingestion_jobs_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_jobs_user_id'), ['user_id'], unique=False)

    op.create_table('rag_queries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('rewritten_query', sa.Text(), nullable=True),
    sa.Column('embedding_model', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('llm_model', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('reranker_model', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('dense_top_k', sa.Integer(), nullable=True),
    sa.Column('sparse_top_k', sa.Integer(), nullable=True),
    sa.Column('fused_top_n', sa.Integer(), nullable=True),
    sa.Column('reranker_top_k', sa.Integer(), nullable=True),
    sa.Column('results_count', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('access_scope', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('timings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['rag_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['rag_messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rag_queries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rag_queries_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rag_queries_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rag_queries_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rag_queries_user_id'), ['user_id'], unique=False)

    op.create_table('ingestion_stages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Enum('parse', 'clean', 'chunk', 'embed', 'index', 'finalize', name='ingestionstagename', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', 'skipped', name='stagestatus', native_enum=False, length=32), server_default='pending', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('items_total', sa.Integer(), nullable=False),
    sa.Column('items_processed', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.CheckConstraint('items_total >= 0 AND items_processed >= 0', name='ck_ingestion_stages_items'),
    sa.ForeignKeyConstraint(['job_id'], ['ingestion_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'stage', name='uq_ingestion_stages_job_stage')
    )
    with op.batch_alter_table('ingestion_stages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingestion_stages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_stages_job_id'), ['job_id'], unique=False)

    op.create_table('rag_citations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('chunk_id', sa.UUID(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('citation_text', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.CheckConstraint('rank >= 1', name='ck_rag_citations_rank'),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['rag_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'rank', name='uq_rag_citations_message_rank')
    )
    with op.batch_alter_table('rag_citations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rag_citations_chunk_id'), ['chunk_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rag_citations_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rag_citations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rag_citations_message_id'), ['message_id'], unique=False)

    with op.batch_alter_table('AuditLog', schema=None) as batch_op:
        batch_op.alter_column('details',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_audit_log_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_resource_type'))
        batch_op.drop_index(batch_op.f('ix_audit_log_timestamp'))
        batch_op.create_index(batch_op.f('ix_AuditLog_id'), ['id'], unique=False)

    with op.batch_alter_table('RoleGroup', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_rolegroup_name'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_RoleGroup_name'))
        batch_op.create_index(batch_op.f('ix_RoleGroup_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('RoleGroup', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_RoleGroup_name'))
        batch_op.create_index(batch_op.f('ix_RoleGroup_name'), ['name'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_rolegroup_name'), ['name'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('AuditLog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_AuditLog_id'))
        batch_op.create_index(batch_op.f('ix_audit_log_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_resource_type'), ['resource_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_actor_id'), ['actor_id'], unique=False)
        batch_op.alter_column('details',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)

    with op.batch_alter_table('rag_citations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rag_citations_message_id'))
        batch_op.drop_index(batch_op.f('ix_rag_citations_id'))
        batch_op.drop_index(batch_op.f('ix_rag_citations_document_id'))
        batch_op.drop_index(batch_op.f('ix_rag_citations_chunk_id'))

    op.drop_table('rag_citations')
    with op.batch_alter_table('ingestion_stages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingestion_stages_job_id'))
        batch_op.drop_index(batch_op.f('ix_ingestion_stages_id'))

    op.drop_table('ingestion_stages')
    with op.batch_alter_table('rag_queries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rag_queries_user_id'))
        batch_op.drop_index(batch_op.f('ix_rag_queries_message_id'))
        batch_op.drop_index(batch_op.f('ix_rag_queries_id'))
        batch_op.drop_index(batch_op.f('ix_rag_queries_conversation_id'))

    op.drop_table('rag_queries')
    with op.batch_alter_table('ingestion_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingestion_jobs_user_id'))
        batch_op.drop_index('ix_ingestion_jobs_status_created')
        batch_op.drop_index(batch_op.f('ix_ingestion_jobs_source_id'))
        batch_op.drop_index(batch_op.f('ix_ingestion_jobs_job_type'))
        batch_op.drop_index(batch_op.f('ix_ingestion_jobs_id'))
        batch_op.drop_index(batch_op.f('ix_ingestion_jobs_document_id'))
        batch_op.drop_index('ix_ingestion_jobs_celery_task')

    op.drop_table('ingestion_jobs')
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_chunks_id'))
        batch_op.drop_index('ix_document_chunks_hash')
        batch_op.drop_index(batch_op.f('ix_document_chunks_document_id'))

    op.drop_table('document_chunks')
    with op.batch_alter_table('document_acl', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_acl_user_id'))
        batch_op.drop_index(batch_op.f('ix_document_acl_id'))
        batch_op.drop_index(batch_op.f('ix_document_acl_granted_by_id'))
        batch_op.drop_index(batch_op.f('ix_document_acl_document_id'))

    op.drop_table('document_acl')
    with op.batch_alter_table('source_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_credentials_source_id'))
        batch_op.drop_index(batch_op.f('ix_source_credentials_id'))

    op.drop_table('source_credentials')
    with op.batch_alter_table('rag_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rag_messages_id'))
        batch_op.drop_index(batch_op.f('ix_rag_messages_conversation_id'))
        batch_op.drop_index('ix_rag_messages_conversation_created')

    op.drop_table('rag_messages')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index('uq_documents_source_external', postgresql_where=sa.text('source_id IS NOT NULL AND external_id IS NOT NULL AND deleted_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_documents_status'))
        batch_op.drop_index(batch_op.f('ix_documents_source_type'))
        batch_op.drop_index(batch_op.f('ix_documents_source_id'))
        batch_op.drop_index(batch_op.f('ix_documents_owner_id'))
        batch_op.drop_index(batch_op.f('ix_documents_id'))
        batch_op.drop_index('ix_documents_collection_status')
        batch_op.drop_index(batch_op.f('ix_documents_collection_id'))
        batch_op.drop_index('ix_documents_collection_hash')

    op.drop_table('documents')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index('uq_sources_type_external', postgresql_where=sa.text('external_id IS NOT NULL'))
        batch_op.drop_index(batch_op.f('ix_sources_type'))
        batch_op.drop_index(batch_op.f('ix_sources_id'))
        batch_op.drop_index(batch_op.f('ix_sources_default_collection_id'))
        batch_op.drop_index(batch_op.f('ix_sources_created_by_id'))
        batch_op.drop_index('ix_sources_active_next_sync')

    op.drop_table('sources')
    with op.batch_alter_table('rag_conversations', schema=None) as batch_op:
        batch_op.drop_index('ix_rag_conversations_user_updated')
        batch_op.drop_index(batch_op.f('ix_rag_conversations_user_id'))
        batch_op.drop_index(batch_op.f('ix_rag_conversations_id'))
        batch_op.drop_index(batch_op.f('ix_rag_conversations_collection_id'))

    op.drop_table('rag_conversations')
    with op.batch_alter_table('collection_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_collection_members_id'))
        batch_op.drop_index(batch_op.f('ix_collection_members_collection_id'))

    op.drop_table('collection_members')
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collections_visibility'))
        batch_op.drop_index(batch_op.f('ix_collections_owner_id'))
        batch_op.drop_index(batch_op.f('ix_collections_id'))

    op.drop_table('collections')
    # ### end Alembic commands ###
